viewport/viewport.go
When I first started attempting to use Glow to read Markdown, the first thing I did was try to scroll. I've been trained for years to use <C-d>, <C-u> to scroll... This lets those binding work.
=> add a couple alternate key bindings to make the scrolling more intuitive

paginator/paginator.go, spinner/spinner.go, viewport/viewport.go
This generally means that `View()` and `Update()` exist as methods on the model rather than standalone functions.
=> Idiomatic design updates per Bubble Tea v0.12.0

go.mod, go.sum, spinner/spinner.go, textinput/textinput.go
This PR introduces Lip Gloss for styling in the Spinner and Text Input components, allowing for greater range in styling, and simpler code internally.
This update introduces some minor API changes, however functionality remains the same.
`Model.ForegroundColor` and `Model.BackgroundColor` is now simply `Model.Style`.
* `Model.TextColor` is now `Model.TextStyle`, allowing for a greater range in input text styling
* `Model.PlaceholderColor` is now `Model.PlaceholderStyle`, allowing for a greater range in placeholder styling
* `Model.CursorColor` is now `Model.CursorStyle`, allowing for a greater range in cursor styling
* Added `Model.PromptStyle`. Previously, styling the prompt was left as an exercise for the user.
=> Use Lip Gloss for styling in Spinner and Text Input

viewport/viewport.go
This PR prevents a panic in the viewport that could occur when setting content without resetting the y-offset.
This was discovered in charmbracelet/bubbletea#87.
=> Keep y-offset in bounds when setting content in viewport

textinput/textinput.go
This is a minor PR that and improves the textinput API and improves behavior when dealing with masked input, such as password input.
Changed:
* `SetCursor(int)`, `CursorStart()` and `CursorEnd()` no longer return values.
* If `EchoMode` is not `EchoNormal` word-to-word movement instead jumps to the beginning and end. Word-based deletion instead deletes to the beginning and end.
New:
* `Cursor() int` returns the cursor position.
Removed:
* Removed `Cursor string`, which did absolutely nothing.
=> Minor textinput improvements

README.md, spinner/spinner.go, textinput/textinput.go
This PR introduces options for textinput cursor behavior and improves subtleties with cursor blinking when multiple textinputs are present.
* Cursors now have three modes: `CursorBlink`, `CursorStatic` and `CursorHide` (all of type `CursorMode`). You can set the cursor mode via `textinput`’s `Model.SetCursor(CursorMode)` and get the cursor mode with `Model.CursorMode() CursorMode`.
* `textinput`’s `Model.Focus()` is now `Model.Focus() tea.Cmd`. This will initiate a properly timed cursor blink when focusing on a textinput if the cursor mode is set to blink.
* After their initial cursor blink (initiated by `textinput.Blink() tea.Cmd`), textinputs can now only receive blink messages they sent. This prevents textinputs from receiving other textinputs blink messages when focus changes.
* When …
=> Textinput Cursor Enhancements

go.mod, go.sum, progress/progress.go
This update leverages the newly-released [Harmonica](https://github.com/charmbracelet/harmonica) to animate the progress bar between states as well as some general improvements to the `progress` package.
* The progress bar can now be animated:
* `Model.SetPercent()` starts the animation (as well as `Model.IncrPercent()` and `Model.DecrPercent()`)
* `FrameMsg`s sent to `Model.Update()` step the animation.
* Customize animation settings can be set via `SetSpringOptions`. See the [Harmonica README](https://github.com/charmbracelet/harmonica) for details on spring settings.
* You can now use [Lip Gloss](https://github.com/charmbracelet/lipgloss) to style the percentage readout: `Model.PercentageStyle` is now of type `lipgloss.Style`.
* `Model.View` is now `Model.ViewAs`. This can be used to …
=> Progress bar can now optionally animate itself

README.md, help/help.go, key/key.go
A customizable horizontal mini help view that automatically generates itself
from your keybindings. It features single and multi-line modes, which the user
can optionally toggle between. It will truncate gracefully if the terminal is
too wide for the content.
A non-visual component for managing keybindings. It’s useful for allowing users
to remap keybindings as well as generating help views corresponding to your
keybindings.
```go
type KeyMap struct {
Up key.Binding
Down key.Binding
}
var DefaultKeyMap = KeyMap{
Up: key.NewBinding(
key.WithKeys("k", "up"),
key.WithHelp("↑/k", "move up"),
),
Down: key.Binding{
WithKeys("j", "down"),
WithHelp("↓/j", "move down"),
},
}
func (m Model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
switch msg := msg.(type) {
case tea.KeyMsg:
switch {
case …
```
=> Add simple helper package for making user-definable keymappings and help bubble

README.md, key/key.go
This mini PR corrects README and GoDoc keybinding examples
=> Fix keybinding examples

progress/progress.go
This is a minor update to the (imminently released) animatable progress bar for composability purposes.
=> Progress bars now statisfy the tea.Model interface

timer/timer.go
closes #22 
A simple timer component:
- ticks every second
- on timeout, executes the given `tea.Cmd`
Simplest possible usage example:
```go
package main
import (
"fmt"
"os"
"time"
"github.com/charmbracelet/bubbles/timer"
tea "github.com/charmbracelet/bubbletea"
)
func main() {
m := timer.Model{
Timeout: 10 * time.Second,
OnTimeout: func() tea.Cmd {
return tea.Quit
},
}
if err := tea.NewProgram(m).Start(); err != nil {
fmt.Println("Oh no, it didn't work:", err)
os.Exit(1)
}
}
```
let me know what you think
=> feat: simple timer component

stopwatch/stopwatch.go
follow up of #67, a simple stopwatch component
=> feat: stopwatch

viewport/viewport.go
This update fixes a bug where final lines wouldn't be rendered in viewports when doing standard (non-performance) rendering. I supposed we never noticed this because many of our files and strings tended to have a final newline (in the latter case, perhaps to work around the bug).
This update also contains a fix where the performance renderer could consume one line too many if the y-position of the viewport was greater than `0`.
This update also introduces a  method for setting a viewport's y-offset, `Model.ViewSetYOffset(int)`, which contains some safeguards for keeping the y-offset in bounds.
In a future release, the `Model.YOffset` member, an `int`, will be replaced with a getter.
Fixes #73.
=> Fix bug where viewport doesn't render final lines

key/key.go
`key.Binding` currently allows you to bind against multiple keys:
```go
binding := key.Binding(key.WithKeys("q", "ctrl+c"))
```
However, sometimes you may also want to match on multiple bindings at once:
```go
left := key.Binding(key.WithKeys("h", "left"))
right := key.Binding(key.WithKeys("l", "right"))
case key.Matches(msg, left), key.Matches(msg, right):
```
This update expands `key.Matches` to accept multiple arguments so you can condense the above `case` statement to:
```go
case key.Matches(msg, left, right):
```
=> Allow `key.Matches` to accept multiple binding arguments

stopwatch/stopwatch.go
In short, stopwatches will now ignore messages sent by other stopwatches. Additionally, `TickMsg`s, will have IDs allowing developers to determine which stopwatch a given `TickMsg` belongs to.
Additionally, `StartStopMsg` and `ResetMsg` are also now exposed so that those messages can be explicitly routed to stopwatches if desired, eliminating the need to pass all messages through a stopwatch in order for it to function.
=> Add support for multiple stopwatches

spinner/spinner.go
This update associates `spinner.TickMsg`s with with spinners so that spinners will only respond to their own messages. This helps prevent spinners from spinning out of control and allows you to start and stop specific spinners without any logical gymnastics.
As a side effect of this change, the `spinner.Tick` command has been deprecated in favor of `spinner.Model.Tick`:
```go
import `github.com/charmbracelet/bubbles/spinner`
// Deprecated: this will start any spinner that receives the resulting TickMsg
return m, spinner.Tick
// New: start a specific spinner
return m, m.mySpinner.Tick()
```
=> Spin Safety

viewport/keymap.go, viewport/viewport.go
This update contains a number of improvements to the viewport Bubble to make it more pleasant to work with. Keep in mind that as of this update viewport models are strongly encouraged to be initialized with the new `New(width, height int) Model` function, however it's currently optional to reduce friction when upgrading.
```go
const width, height = 40, 80
vp := viewport.New(width, height)
```
* Viewport models now have a `Style lipgloss.Style` property for setting borders, margins, and padding. No more magic numbers, random constants, and awkward arithmetic!
* Keybindings are now defined via the [`key`](https://github.com/charmbracelet/bubbles#key) Bubble and can now be easily remapped.
* The mouse wheel-based scroll speed can now be customized via the model's `MouseWheelDelta int` …
=> Viewport quality-of-life improvements

help/help.go, list/list.go, paginator/paginator.go, progress/progress.go, spinner/spinner.go, textinput/textinput.go
This update changes the `NewModel()` convention in all Bubbles to the to the shorter `New()` function, in-line with @caarlos0's excellent work on the new `timer` and `stopwatch` Bubbles.
```go
before := textinput.NewModel()
after := textinput.New()
```
=> Deprecate NewModel() constructors; use New() instead

list/list.go
Bug: when calling SetItems when items was previously empty, the keybindings for
up/down do not appear.
Fix: call updateKeybindings in SetItems.
=> fix(list): update keybindings when setting items

list/list.go
Hot on the heels of #90, this update fixes a bug in the `list` Bubble where the up/down keybindings would be disabled and hidden in the help if `InsertItem` was called on an empty list.
=> Update keybindings after calling InsertItem on the list model

textinput/textinput.go
* fixes infinite loop when deleting input that only contains whitespace using deleteWordLeft()
* fixes index out of range panic when deleting input that only contains whitespace using deleteWordRight()
=> fix textinput infinite loop and panic

viewport/viewport.go
These fixes address two `viewport` issues, most likely introduced in 0ac5ecd:
* Fix off-by-one errors with regard to `GotoBottom()`
* Fix a bug where the y-offset could be out of bounds 
Thanks to @IllusionMan1212 and @knipferrc for flagging the bugs and helping fix 'em.
=> Viewport bugfixes

textinput/textinput.go, viewport/viewport.go
General tidying up. The notable thing here is that we now ignore width and height set on the `Style` member in a `viewport` model since it can convict with the `Width`and `Height` attributes on the model and result in odd rendering and general confusion. So something like this will no longer result in funny rendering:
```go
const width, height = 40, 80
m := viewport.New(width, height)
m.Style = lipgloss.NewStyle().
Width(width).
Height(height)
```
=> Housekeeping

list/list.go
The fix in #108 resets the quit keybinding _after_ the switch on the filter state. Instead, it should get reset in the switch's default case so it doesn't override turning it off in the filtering state.
=> fix(list): disable quit keybinding while filtering

textinput/textinput.go
As discussed on Slack earlier, this PR adds a `Blink()` method that returns the text input's blink state. This is useful if you want to render something more complex than the existing `View()` method can handle. For context, I'm implementing an input with multiple types of placeholders, each with different styles. I thought about adding something to the text input itself to handle this case, but it would add a lot of complexity for a rather niche use case. With the `blink` property exposed, users can implement their own `View()` method.
=> Add Blink method to textinput to return blink state

progress/progress.go
Prior to this change Percent() returned the target progress to which the progress bar was animating which not necessarily what is visually presented. This change is helpful because it makes it easier to time UI updates with the display of the percentage as the user understands it.
=> chore(progress): Percent() now return progress as presented visually

list/list.go
=> feat(list): allow custom filter functions

spinner/spinner.go
The design was overly complicated, especially for such subtle benefits. Removing this feature simplifies the codebase as well as the codebase of projects that would potentially use this feature.
This (provisional) feature was originally was aded for [Glow](https://github.com/charmbracelet/glow), and because of its complexity there's a high likelihood that there are any other projects taking advantage of it.
=> chore(spinner): remove provisional spinner lifetime stuff

spinner/spinner.go
=> fix(spinner): remove unused member in model

progress/progress.go
Add the ability to set a custom color profile.
`progress.WithColorProfile()`
On unsupported terminals (inside docker, over ssh), `termenv.ColorProfile()` reports the wrong color profile.
=> fix(progress): set a custom termenv color profile

spinner/spinner.go
The doc for spinner.Model.Update is obsolete as per 35c3cd626d97e1a5e39d1fae3e481b3940e525a8,
which made Update aware of Msg's type.
=> docs(spinner): remove obsolete comment

textinput/textinput.go
Based on https://github.com/charmbracelet/bubbles/pull/114
Adds `Validate` property to `textinput` to ensure input is valid.
Validate is a function that accepts a `string` and returns an `error` which may be `nil` if the string is valid.
```go
// ValidateFunc is a function that returns an error if the input is invalid.
type ValidateFunc func(string) error
```
=> Feature: Validate Input

spinner/spinner.go
It appears that spinner's Internal ID comment was accidentally left the same as [textinput's comment](https://github.com/charmbracelet/bubbles/blob/e57fd292cc688c315659ae180eded043369452ac/textinput/textinput.go#L18-L19).
This new comment is taken from [progress.go](https://github.com/charmbracelet/bubbles/blob/e57fd292cc688c315659ae180eded043369452ac/progress/progress.go#L18-L19).
=> docs(spinner): correct comment about internal ID

timer/timer.go
I don't know the details, but when I used Stop function on timer it doesn't stop the timer, but it worked fine if I use Toggle() function instead on a running Timer.
Looking at the code this sounds as it should be this way, but I don't know if I'm doing something wrong os this piece of code should be fixed.
=> Fix timer Stop

list/list.go
It’s correct that can't `quit` by pressing q when filtering, so it seems better to not show `q` in the help while filtering.
=> list: fix to not show up quit in help while filtering

spinner/spinner.go, spinner/spinner_test.go
This PR introduces a `spinner.Option` type that allows passing configuration options when creating new spinners using `spinner.New`. This doesn't break existing code as it uses variadic arguments, so any existing code as the following should continue to work:
```go
s := spinner.New()
s.spinner = spinner.Dot
```
This code now can be written as:
```go
s := spinner.New(spinner.WithSpinner(spinner.Dot))
```
In order not to be overly verbose, a `With` function was defined for each of the pre-existing spinners, so one can have for instance:
```go
s := spinner.New(spinner.withPulse())
```
Last but not least it also adds a `WithStyle(lipgloss.Style)` option function.
This is mostly syntactic sugar, but helps when you have a custom model and want to create it:
```go
func New() MyModel {
return …
```
=> New spinner with option

textinput/textinput.go
This reverts the code back to the logic from 4ce16e8 which fixed the issue of the cursor not being moved when an initial value was set with SetValue.
The fix regressed in 16053f4.
=> fix(textinput): set cursor on initial value

key/key.go
[Unbind()](https://pkg.go.dev/github.com/charmbracelet/bubbles@v0.13.0/key#Binding.Unbind)'ed keys are not usable anymore, so it should not be counted as Enabled. For example, unbound keys should not show up in help.
=> Unbound keys should not be enabled

key/key.go, key/key_test.go
I am very sorry that I wrote wrong condition in https://github.com/charmbracelet/bubbles/pull/188 🙇 
This is a fix for it, Unbound keys has nil keys and they are not Enabled.
=> fix condition for #188

textarea/textarea.go
`CharLimit` documentation states:
```
// CharLimit is the maximum number of characters this input element will
// accept. If 0 or less, there's no limit.
```
However, when `CharLimit` is `0` it does not allow any input.
=> fix: CharLimit <= 0 should be ignored

textarea/textarea.go
Fixes #203
Fixes #202
- fix: include new line characters for Length()
- feat: LineCount method for counting number of lines in textarea
=> LineCount + Include New Line characters in Length()

textarea/textarea.go
The maximum slice size of m.value is the max number of rows,
which is the max height.
cc @maaslalani
=> textarea: fix the pre-allocation of value

textarea/textarea.go
I'm working to make textarea closer to readline/editline conventions (e.g. as used on a shell command line or emacs).
- search prev/next word should find words on the prev/next line if there's no word remaining on the current line.
- Alt+u to uppercase cur/next word
- Alt+l to lowercase cur/next word
- Alt+c to capitalize cur/next word
- Ctrl+t to transpose previous 2 characters
cc @maaslalani
=> textarea: misc improvements

table/table.go
Fixes `pgdown` keybindings and adds keys to help.
=> fix(table): correct keybinding for page down

viewport/viewport.go
This fixes a regression where `viewport`’s width and height settings weren't respected.
=> fix(viewport): honor width and height settings

textarea/textarea.go
Explanation about the chosen bindings:
- Alt+< / Alt+>: These are the same as emacs.
- Ctrl+Home / Ctrl+End: These are the same as some other windows editors.
(For the latter, they will only work after https://github.com/charmbracelet/bubbletea/pull/396 is merged. But this PR can merge ahead of it -- unrecognized bindings are simply ignored for the time being.)
cc @maaslalani
=> textarea: new bindings for "go to begin" / "go to end"

textarea/textarea.go
The secondary prompt is displayed on every line after the first.
See for example:
[![asciicast](https://asciinema.org/a/iFBPBwoDZOzcoRJOgfmPk8ObH.svg)](https://asciinema.org/a/iFBPBwoDZOzcoRJOgfmPk8ObH)
Used in https://github.com/knz/bubbline
cc @maaslalani
=> textarea: support dynamic prompts

viewport/viewport.go
Fixes #227 
- logical content is wider than display width (long lines).
In this case, we truncate.
- logical content is smaller than display height (fewer lines
than visible).
In this case, we pad with empty lines up to the specified height.
- logical content is higher than display height (more lines than
visible).
In this case, we truncate.
- style specifies a width wider than the display width.
In this case, we ignore the style width and
fit in the display width.
- style specifies a height higher than the display height.
Same as width, we ignore the style and fit in the display height.
- style specifies a narrower width or smaller height than the display.
In this case we obey the style.
cc @meowgorithm
=> fix(viewport): properly truncate to size

list/list.go, progress/progress.go, spinner/spinner.go, textinput/textinput.go
* Remove internal use of deprecated `NewModel` functions.
* Fix description of `textinput.Model.Focus`.
* Format comments with `go fmt`.
=> chore: Miscellaneous minor fixes

textarea/textarea.go
while trying to put together a program using this bubble, i discovered that the paste function seems to be incomplete (at least, compared to the ``textinput`` paste function), in that it doesn't apply changes to ``textarea.value``.
i just copied the associated code from ``textinput`` to actually apply the changes, it's nothing special.
=> fix: textarea paste

textinput/textinput.go
Fixes #269.
cc @muesli @maaslalani
=> feat: support key bindings in textinput like textarea

paginator/paginator.go
Fixes #271.
This will also make the paginator benefit from the improvement in #261.
cc @maaslalani @meowgorithm
=> feat: make the paginator key bindings customizable

viewport/viewport.go
[As per discord discussion](https://discord.com/channels/1032368467246075914/1032368467988451425/1037767861030096976), exposes a `TotalLineCount()` and `VisibleLineCount()` methods in the viewport package.
=> Expose TotalLineCount() and VisibleLineCount() methods within viewport

runeutil/runeutil.go, runeutil/runeutil_test.go, textarea/textarea.go, textinput/textinput.go
Completes the fix to https://github.com/charmbracelet/bubbletea/issues/404
https://github.com/charmbracelet/bubbletea/pull/397
Also, informs #263.
cc @muesli @maaslalani
=> feat+fix: bracketed paste in textinput + textarea, avoid ctl chars in clipboard input

textarea/textarea.go
My previous fix did not properly handle a multi-rune input that *ends* with a newline character. In that case, the final newline was removed.
I found this using the test suite I built for textarea in bubbline at https://github.com/knz/bubbline/tree/main/editline/internal/textarea/testdata.
cc @maaslalani @muesli
=> fix(textarea): support pastes that end with a newline character

textarea/textarea.go
Found using the unit test suite at https://github.com/knz/bubbline
Previously, when inserting multiple lines of input at once, the underlying Go data array was incorrectly shared in memory across multiple rows of the textarea. This was causing input corruption, where a user trying to modify one line would see their text added on the next line as well.
This patch fixes it.
cc @maaslalani
=> fix(textarea): fix data corruption after multi-line input

cursor/cursor.go, help/help.go, list/defaultitem.go, list/keys.go, list/list.go, paginator/paginator.go, progress/progress.go, runeutil/runeutil.go, stopwatch/stopwatch.go, table/table.go, textarea/textarea.go, textarea/textarea_test.go, textinput/textinput.go, timer/timer.go, viewport/viewport.go
Just wanted to improve the docs 🤙
=> docs: fix typos and improve comment clarity

textinput/textinput.go
I noticed that it seemed like `BackgroundStyle` was unused in `TextInput` and then discovered there was already an open issue for it.
Closes #182
=> Remove unused BackgroundStyle in TextInput

.github/workflows/build.yml, filepicker/filepicker.go, filepicker/hidden_unix.go, filepicker/hidden_windows.go, go.mod, go.sum
Filepicker bubbles allows for selecting files or directories with customizable
key bindings and styling.
It emits a `FileSelectedMsg` to allow the parent model to react to a valid selection action.
=> Filepicker Bubble

table/table.go
* This adds bounds checking to the function returning the row under the cursor. By adding the check, it avoids that the program crashes when calling the function and the cursor is out of bounds.
* The cursor can still become out of bounds values, which is a problem in itself.
=> fix: add bounds checking to the selectedrow func

table/table.go
the `cmds` variable in table's Update method is unused. 
I replaced it with `nil`.
=> refactor(table): remove unused cmds variable

progress/progress.go, progress/progress_test.go
When rendering a progress bar with a gradient, the calculation of the ratio (p) used to determine the color at a given point is off by one. This results in the very last color rendered in a gradient not being the same as the specified second color of the gradient.
This PR adds a test to show this behavior and a fix for the off-by-one calculation.
Fixes #342
=> fix(progress): last gradient color off by one

list/README.md
I added the FAQ to a markdown file in the `list` dir. I *feel* like that's a good spot for it, but definitely open to discussion.
=> docs(list): add FAQ

list/list.go, textinput/textinput.go
Deprecates `CursorStyle` in favour of `Cursor.Style`.
=> fix: deprecate `CursorStyle` in favour of `Cursor.Style`

textarea/textarea.go
Over at CockroachDB we're finding needs for textareas with hundreds of input lines.
cc @maaslalani
=> feat(textarea): make max width/height configurable

textarea/textarea.go, textinput/textinput.go
Fixed the issue where cursor showing up when moved despite `cursor.Mode == CursorHide`.
=> fix(textarea/textinput): Reset blink only when CusrorBlink

progress/progress.go
This would be useful to know to stop displaying it after the user was shown the progress bar to render to its end.
Solution: expose `IsComplete` method is based on what's been drawn
=> Problem: can't determine if the progress bar stopped updating

list/list.go
Change list wording to read `No items.` as opposed to `No items found.`
=> fix: No items found. -> No items.

list/list.go
As the number of items in `targets` is known, use `make` with the expected size instead of appending, which requires more allocations as the `targets` slice grows.
=> perf(list): reduce allocations in `filterItems`

textinput/textinput.go
Continuation of discussion from here: https://github.com/charmbracelet/bubbles/pull/140
=> Support suggestions and autocompletion in textinput

textinput/textinput.go
This PR fixes this [issue](https://github.com/charmbracelet/bubbles/issues/358) regarding textinput resizing based on the placeholder. The original behavior is documented in the issue and has been modified to the following:
`Placeholder = ""`
`Placeholder="123"`
`Placeholder = "1234567890"`
=> fix (textinput): do not resize based on placeholder

list/list.go, textinput/textinput.go
Previously, the `placeholderView()` function did not respect `Width` when it was set to a non-zero value.  The textinput's width now stays the same irrelevant of the placeholder length.
Pasting now trims to match the available space if length is greater than the `charLimit`.
=> fix(textinput): Placeholder No Longer Changes Width + Paste Calculation

viewport/viewport.go
I have an application that uses the viewport, and I added borders to the viewport. I noticed the width is not set to what can be set through `.Width()`, as I'm loading variable width content, which shrinks and grows depending on what it currently renders.
My initial workaround was to force the style from the viewport to set a fixed width. However, that didn't work. Then, I added spaces to the last line of the content to match the viewport's width, which worked, but I believe the end-user code shouldn't be handling this case.
So, with this PR, I'm padding the width of the viewport content to what has been specified in its `width`. Please look at the screenshots from a minimal application reproducing the issue.
Before:
After:
And this is the code that reproduces the issue:
```golang
package …
```
=> fix(viewport): pad width to contentWidth

textinput/textinput.go
As the number of items in `suggestions` and `m.suggestions` is known, we can use `make` with the expected size instead of appending, which requires more allocations as the slice grows.
=> refactor(textinput): reduce allocations

textinput/textinput.go
Uses `uniseg.StringWidth` for performance improvements.
=> Use `uniseg.StringWidth`

paginator/paginator.go
Adds an `OnFirstPage` method to use with `OnLastPage` for better code clarity.
Before:
```go
if g.paginator.OnLastPage() {
// ...
} else if g.paginator.Page == 0 {
// ...
}
```
After:
```go
if g.paginator.OnLastPage() {
// ...
} else if g.paginator.OnFirstPage() {
// ...
}
```
=> Add Paginator OnFirstPage method

progress/progress.go
This is a simple change adding a function, WithCustomFillCharacters, to configure the characters the progress bar is made from. The function takes two runes as parameters for setting m.Full and m.Empty, respectively.
In other words, this adds the option to create a progress bar using any desired characters to represent the full and empty portions of the bar.
This is my first contribution to a larger public project, so please let me know if I went about creating this pull request correctly.
=> feat(progress): make full/empty fill characters configurable

go.mod, go.sum, textarea/textarea_test.go
Add improved unit tests for textarea view function.
The end of buffer unit test was flawed and failed to properly check whether the end of buffer character was in the correct location. This test has been removed as this feature is now verified as part of these test cases.
=> test(textarea): Add tests for textarea view

textarea/textarea.go, textarea/textarea_test.go
This PR aligns the end of buffer character, similar to vim.
Thanks to @mikelorant for the tests and finding the bug.
=> End of Buffer alignment

paginator/paginator_test.go
=> Add tests for paginator

list/list.go
1. Set receivers for list.NextPage and list.PrevPage to pointers
The Next and Prev list functions should advance or move back the page, but with the receivers not being pointers, it causes these methods to be no-ops
=> Fix list pagination functions

cursor/cursor.go
The SetMode method in the cursor library does not handle invalid (out of range values of `Mode` type) mode values correctly. When an invalid mode value is provided, the method should adjust it to a valid value (CursorBlink to CursorHide) or return an error to indicate the issue. However, the current implementation does not enforce this behavior, potentially leading to unexpected results.
- Instantiate a cursor model.
- Call the SetMode method with an invalid mode value (e.g., less than CursorBlink or greater than CursorHide). `cursor.SetMode(-1)`
- Verify the behavior of the method.
If an invalid mode value is provided, the SetMode method should either adjust it to a valid value within the range (CursorBlink to CursorHide) or return an error to indicate the issue.
The SetMode method does …
=> fix: Bug: SetMode method in cursor library does not handle invalid mode values correctly

textarea/textarea.go, textarea/textarea_test.go
The end of buffer character was not being rendered when line numbers were not enabled.
When the new test tables unit tests were created this issue was identified however to limit the scope of those changes to just creating unit tests, this regression was maintained.
This change fixes this issue and updates the tests to the intended result.
=> fix(textarea): Fix end of buffer character

textinput/textinput.go
This PR enables <kbd>ctrl+left</kbd> for `WordBackward` and <kbd>ctrl+right</kbd>
for `WordForward`.
NB: theoretically this should work but I didn't see this work in Kitty, iTerm,
or terminal.app.
=> Ctrl+Left/Right for WordForward/Backward

textarea/textarea_test.go
Improve textarea tests to check the cursor location. This is the displayed location and not the line row and column (which does not take into account soft wrapping).
As part of this improvement, a number of existing tests were merged into the view test tables as it was unnecessary duplication of code having them separated.
=> test(textarea): Improve textarea tests

viewport/viewport.go
In the current implementation one gets a division by zero in case `len(m.lines) == m.Height + 1`, which in turn makes the function return `NaN`.
Removing the `-1` does avoid this error and still yields sensible results.
=> Fix division by zero in viewport scrollpercentage calculation

table/table.go
I spotted a bug while creating a table and viewport side by side. Even though they have set the exact height value, both have different sizes. While debugging, it came out that we only passed it down to the nested viewport component by setting table height, but the render method looks like this.
```
// View renders the component.
func (m Model) View() string {
return m.headersView() + "\n" + m.viewport.View()
}
```
So, the total height of the table is the sum of the viewport's height and the headers' height. I have simply subtracted headings Y size from the viewport height, and it looks like this fixed the issue.
=> fix(table): substract headers Y size from the total table size

table/table.go
The previous version of the code used the SetYOffset function of the table's viewport, which caused the viewport to scroll up before the selected reached the top.
Fix: #428
=> fix(table): table scrolls before selected reaches top/bottom

textinput/textinput.go
This PR builds upon the excellent work in https://github.com/charmbracelet/bubbles/pull/167 and https://github.com/charmbracelet/bubbles/pull/114 and makes a breaking change to the validation API.
Currently, validation will completely block text input if the Validate function returns an error. This is now changed so the function no longer blocks input if this is the case, thus handing this responsibility to the clients.
This is helpful for cases where the user is requested to type an existing system path, and the `Validate` function keeps asserting the existence of the path. With the current implementation such a validation is not possible.
For example:
> /
Err: nil
> /t
Err: /t: No such file or directory
> /tm
Err: /tm: No such file or directory
> /tmp
Err: nil
=> feat(textinput): do not block input on validation

textarea/textarea.go, textarea/textarea_test.go
When setting the width of the textarea there were some issues preventing this from working correctly. These problems included:
- If the maximum width needed to be used, the width of the textarea did not take into account the prompt and line number width.
- The viewport width did not take into account the style width.
The entire function was confusing to understand and a refactor was warranted.
As part of this refactor, the bugs mentioned above were fixed and the code was simplified.
To verify that the logic works as expected, unit tests were expanded to validate that setting the width works as expected.
=> refactor(textarea): Improve setting width

help/help.go
The help bubble appends the separator after the final column, which results in it being shifted 4 cols to the left when centered. This PR removes the final separator column.
I don't know the reasoning for this decision, so feel free to close this if the final separator column is intended! If it is, maybe a bool should be added to toggle the behavior?
Fixes #415
Thank you!
<details>
<summary>ascii-movie</summary>
I built [ascii-movie](https://github.com/gabe565/ascii-movie), and have seen this behavior. Here's a screenshot before and after the fix:
**Before:**
**After:**
</details>
<details>
<summary>simple repro</summary>
**Before/After:**
**Code:**
```go
package main
import (
"fmt"
"os"
"github.com/charmbracelet/bubbles/help"
"github.com/charmbracelet/bubbles/key"
tea …
```
=> fix(help): Fix help bubble not centering correctly

textarea/textarea.go, textarea/textarea_test.go
This changes the default `EndOfBufferCharacter` to a space character. I tend to agree with the conclusion in #491 that this is probably a better default.
Happy to discuss if this isn't the direction you want to go @maaslalani.
=> fix: default textarea EndOfBufferCharacter should be ' '

textarea/textarea.go, textarea/textarea_test.go
Add the capability to show a multiline placeholder. Some refactoring was required to improve readability and improve logic.
End of line buffer character was only shown when line numbers were displayed which requires some verification whether this is the intended outcome. This change resolves this issue.
=> feat(textarea) Add multiline placeholder

progress/progress.go
In progress component constructor, default spring option must be handled *after*  applying options :)
Indeed, the `springCustomized` variable is set by the option `WithSpringOptions`.
=> fix: progress spring defaults should't override WithStringOptions

table/table.go
resolves #538 
result from this PR:
=> fix(table): inherit SelectedStyle for StyleFunc

table/table.go
This PR fixes: https://github.com/charmbracelet/bubbles/issues/553
Ideally, JoinHorizontal should expect `Top`, `Bottom`, or `Center` positions. This PR fixes the cases where the `Left` position constant was used instead of `Top`.
Also while reviewing the JoinHorizontal function I noticed there were no unit tests for JoinHorizontal, so in the linked PR, I added the unit test for the same in lipgloss.
Lipgloss PR: https://github.com/charmbracelet/lipgloss/pull/346
=> fix: update position constant in JoinHorizontal

key/key.go
This allows any `fmt.Stringer` interface to match key bindings. We need this in the upcoming v2 changes.
=> feat(key): accept any stringer interface to match keys

paginator/paginator.go, paginator/paginator_test.go
Introduce paginator options, to ease instanciation.
```go
p := paginator.New(
paginator.WithPerPage(42),
paginator.WithTotalPages(42),
)
```
Only these two options has been added, but other could be easily added now that the foundations has been laid :)
Note: to be honnest, i don't know if you prefer such integration, or the "chain" one like:
```go
p := paginator.New().WithPerPage(42).WithTotalPages(42)
```
I see bof of them in current charmbracelet ecosystem, just tell me :)
=> feat: Introduce paginator options

.golangci-soft.yml, .golangci.yml
Linter output for this change:
* The linter "deadcode" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
* The linter "structcheck" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
* The linter "varcheck" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
* The linter 'gomnd' is deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd.
=> chore(lint): update mnd name, remove deprecated directives

list/list.go, list/list_test.go
Currently, there's no way to allow a developer to prefill a list filter reliably. A workaround of using Program.Send works, but is limiting.
This PR introduces two new functions, SetFilterText and SetFilterState which fix this issue and allow for finer control over the list's initial filter state.
Willing to make whatever style changes etc. are required.
=> Add SetFilterText and SetFilterState

.golangci.yml, viewport/viewport.go
Performance rendering is to be deprecated in Bubble Tea. Details here: https://github.com/charmbracelet/bubbletea/pull/1138.
=> chore(viewport): deprecate performance rendering stuff

textinput/textinput.go
In its current state, if I want to get the matched suggestions (and their index) I need to recalculate that myself when the bubble already does this for free (as in already available). This allows to use the matching suggestions data to display any sort of custom views.
For example, in its current state, if I want to list the suggestions I only have access to the `Available` ones, and this is all I can display (without recalculating myself):
With these exposed methods, now I can display more "complex" views, such as:
Pardon the styling, just a placeholder.
=> feat(textinput): expose matched suggestions and index

filepicker/filepicker.go, progress/progress.go, spinner/spinner.go, stopwatch/stopwatch.go, timer/timer.go
#622 won't work with go 1.18, this should.
based on PR by @weezel 
closes #622
=> fix: use atomic package for ids

table/table.go
It is identical to the second case
=> chore: Remove duplicate and redundant code

list/list.go
This commit introduces a new `filteredItem` field called `index` which stores the index of the filtered item in the unfiltered list. This allows to get at runtime the unfiltered list index for the selected (and possibly filtered) item.
This is the only solution I found to use `SetItem` with a filtered list.
The name `GlobalIndex` might not be ideal, I'm happy to change it to something else. (`UnfilteredIndex`?)
Fixes: #550
<details><summary>Example</summary>
Consider the following code:
```go
package main
import (
"fmt"
"io"
"log"
"os"
"github.com/charmbracelet/bubbles/list"
tea "github.com/charmbracelet/bubbletea"
)
type item struct {
title   string
checked bool
}
func (i item) Title() string       { return i.title }
func (_ item) Description() string { return "" }
func (i item) …
```
=> feat(list): implement GlobalIndex helper

help/help.go
No matter the available horizontal space, sometimes the separator for the full help is not rendered. For example:
The issue is that the check if a separator needs to be rendered is done on `group` (the column) and not `groups` (the total columns). With this fixed:
However, when there is enough space for the separator but not the column itself it renders the separator at the end:
This PR fixes these 2 issues and matches the behavior of the short help (adding a tail if needed/possible, rendering the separator inline, etc.). Behavior now:
=> fix(help): wrong full help sep rendering

go.mod, go.sum, viewport/viewport.go
This breaks the API and removes high performance rendering and its related methods from the viewport package. It changes the API and makes the methods return nothing instead of lines to render.
=> (v2) refactor!: viewport: remove deprecated HighPerformanceRendering

filepicker/filepicker.go, list/list.go, paginator/paginator.go, progress/progress.go, progress/progress_test.go, spinner/spinner.go, stopwatch/stopwatch.go, table/table.go, textarea/textarea.go, textinput/textinput.go, timer/timer.go, viewport/viewport.go
This is a set of breaking changes to enforce consistency and best practices in Bubbles v2.
The two big package-wide ones are:
1. All bubbles now use getters and setters for width and height. This will prevent us from having to make breaking changes in the future when changing size needs to affect other parameters.
```go
// Before
type Model struct {
Height int
}
// After
func (m Model) Height() int
func (m *Model) SetHeight(int)
```
2. Default keymaps are no longer global. This guards against the default keycap being altered on the package level.
```go
// Before
var DefaultKeyMap = KeyMap{/* ... */}
// After
func DefaultKeyMap() KeyMap
```
There are also a series of small package-level adjustments which we'll outline in the release notes.
=> (v2) consistency and best practices

stopwatch/stopwatch.go, timer/timer.go
This keeps them from ticking too fast if they're sent successive starts and stops.
Fixes #661.
=> fix: debounce stopwatch and timer

textinput/textinput.go, textinput/textinput_test.go
Fixes: #531
Fixes: https://github.com/charmbracelet/gum/issues/591
- Manually assigned `p` with the size of the `Width + 1` because when you use `var()` to assign, the cap defaults to 32 and thus it is possible to get out of bounds errors.
=> fix(textinput): slicing outside cap

go.mod, go.sum, progress/progress.go, progress/progress_test.go
This removes the dependency on termenv and replaces it with lipgloss. This change also removes the WithColorProfile option, as it is no longer needed. The new API uses `color.Color` types for colors, which are more flexible and allow for more advanced color manipulation.
=> (v2) chore(progress)!: migrate progress to lipgloss

go.mod, go.sum, viewport/keymap.go, viewport/viewport.go, viewport/viewport_test.go
=> feat(viewport): horizontal scroll

viewport/viewport.go
If the viewport has borders, they are not currently taken into account when calculating the viewport max y offset, which might cause the last line to not be visible.
This is easily reproducible in `gum pager`.
=> fix(viewport): scroll to last line when borders

stopwatch/stopwatch.go
stopwatch currently has a non deterministic way of starting. This is easily fixed by using `tea.Sequence` instead of `tea.Batch`.
timer is not affected as it doesn't use batch on `Start()`
Relevant code parts from stopwatch's file:
```go
// Start starts the stopwatch.
func (m Model) Start() tea.Cmd {
return tea.Batch(func() tea.Msg {
return StartStopMsg{ID: m.id, running: true}
}, tick(m.id, m.tag, m.Interval))
}
...
func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
...
case TickMsg:
if !m.running || msg.ID != m.id {
break
}
...
}
```
Batch's description:
> Batch performs a bunch of commands concurrently **with no ordering guarantees** about the results.
So what basically happens is sometimes `TickMsg` arrives before `StartStopMsg`, as `running` is still `false` this is thrown away. …
=> fix: stopwatch.Start()

progress/progress.go
This conforms to the new generic bubbletea API.
See https://github.com/charmbracelet/bubbletea/pull/1298
=> refactor: progress: return Model instead of tea.Model

cursor/cursor.go, textarea/textarea.go, textinput/textinput.go
This revision adds the missing pieces necessary for `textarea` to support a real cursor. Additionally, `Model.TextStyle` in the `cursor` package was renamed to `Model.BlinkedStyle` for clarity.
=> (v2) textarea,cursor: wrap up real cursor API

README.md, cursor/cursor.go, go.mod, go.sum, progress/progress.go, stopwatch/stopwatch.go, textarea/textarea.go, viewport/viewport.go
This brings textarea API updates (and other stuff on `v2-exp`) into `v2-area`.
=> (v2) merge textarea API updates into v2-area

viewport/viewport.go
Since LeftGutterFunc is public, it can be nil if viewport is instantiated without using `viewport.New()`. This commit adds nil checks to handle this case.
=> fix(viewport): handle nil LeftGutterFunc

.github/workflows/build.yml, .github/workflows/coverage.yml, filepicker/filepicker.go, go.mod, go.sum, list/list.go, list/list_test.go, paginator/paginator.go, progress/progress.go, table/table.go, textarea/textarea.go, textinput/textinput.go, viewport/viewport.go
i think we can use this breaking change to also update go to a more recent version.
go 1.18 is from 2022, go 1.22 is from early last year (~1 year old)
this also allows to delete the `min` and `max` funcs all over the place...
=> feat(v2)!: update to go 1.22

filepicker/filepicker.go
Setting `picker.Height` directly might lead to a bad `picker.max`, which then breaks scrolling.
Found this working on huh, btw :)
=> fix(filepicker): properly scrolling filepicker

textinput/textinput_test.go
Here's what the godoc looks like with this change:
@meowgorithm mentioned wanting to clarify usage for textinput's `Validate` in https://github.com/charmbracelet/bubbles/issues/481. This PR includes an example from Bubble Tea's [credit card example](https://github.com/charmbracelet/bubbletea/blob/main/examples/credit-card-form/main.go)
=> docs: add example for ValidateFunc

textarea/textarea.go, textarea/textarea_test.go, viewport/viewport.go, viewport/viewport_test.go
- make sure all scrolling methods are called `Scroll<direction>`
- renamed `ViewUp` et al to what they actually do (`PageUp`, `HalfPageUp`, etc)
- remove `ResetHorizontalScroll` as we have `SetXOffset`
- deprecated other methods using the deprecated high performance renderer
~~Maybe `SetXOffset` and `SetYOffset` should be unified in `SetScroll(x, y)`?~~ Decided not to do this.
Also, should horizontal scroll be disabled by default? (currently isn't) - ✅ done
=> fix(viewport): normalize method names

table/table.go
The following brings:
- Preventing table's cursor from being out-of-bound when the table's rows shrink.
=> fix(table): preventing cursor from being out-of-bounds.

cursor/cursor.go, cursor/cursor_test.go
The original [Model.BlinkCmd] implementation returned a closure over the pointer receiver:
return func() tea.Msg {
defer cancel()
<-ctx.Done(
if ctx.Err() == context.DeadlineExceeded {
return BlinkMsg{id: m.id, tag: m.blinkTag}
}
return blinkCanceled{}
}
A race on “m.blinkTag” will occur if:
1. [Model.BlinkCmd] is called e.g. by calling [Model.Focus] from ["github.com/charmbracelet/bubbletea".Model.Update];
2. ["github.com/charmbracelet/bubbletea".handleCommands] is kept sufficiently busy that it does not recieve and execute the [Model.BlinkCmd] e.g. by other long running command or commands;
3. at least [Mode.BlinkSpeed] time elapses;
4. [Model.BlinkCmd] is called again;
5. ["github.com/charmbracelet/bubbletea".handleCommands] gets around to receiving and executing the original closure. …
=> fix(cursor): fix data race on blinkTag

textarea/textarea.go
This commit exposes the MoveToBegin and MoveToEnd methods in the textarea package, allowing users to programmatically move the cursor to the beginning or end of the input text.
=> feat(textarea): expose MoveToBegin and MoveToEnd methods

textarea/textarea.go, textarea/textarea_test.go
This ensures that the viewport content is set and persisted correctly. Setting the content during View doesn't work because it mutates a copy of the model instead without persisting the changes. Moreover, any after effects of setting the content won't be visible because the next Update will be called on the older model, not the new one.
=> fix(textarea): ensure viewport content is set during update
