.github/workflows/build.yml, .github/workflows/lint.yml, .golangci.yml
=> Add GitHub workflows

textinput/textinput.go
EchoModes are:
- EchoNormal, displays text as is
- EchoPassword, displays EchoCharacter mask instead of actual characters
- EchoNone, displays nothing
Fixes #10.
=> Add an EchoMode and EchoCharacter property to textinputs

go.mod, go.sum, textinput/textinput.go
Fixes #14. Note that this also required [a bugfix in Bubble Tea proper](https://github.com/charmbracelet/bubbletea/commit/a1d92e77c514ab77c2631ed7c5193adec8e7f50b).
=> Textinput: bind home/end and fix behavior of delete key

textinput/textinput.go
This improves the UX because you never lose track of the cursor
moving around while it's currently hidden.
=> Make textinput cursor visible whenever it changes its position

textinput/textinput.go
* Fix panic when pasting into a textinput with no char limit
* Fix regression where cursor was misplaced after a paste
=> Paste improvements: fix panic and cursor positioning

textinput/textinput.go
Ctrl-W: deletes word left of cursor
Alt-D: deletes word right of cursor
=> Support Ctrl-W and Alt-D to delete words left/right of cursor

paginator/paginator.go
...when the given number of items is below 1.
=> Return the value of paginator.TotalPages in SetTotalPages

go.mod, go.sum, textinput/textinput.go
Note that we're currently pinning Bubble Tea @ master. This should be updated once we release on the Bubble Tea side.
=> Update textinput for multi-char IME input support

spinner/spinner.go
* Keep spinner from spinning super fast if it's receiving more messages than it should be. This can happen when one spinner is being used for multiple things.
* When using advanced hide/show rules, draw a blank space for a spinner when it shouldn't be rendered. This will remove the need for some extra view logic in applications that implement the spinner.
=> Spinner improvements

textinput/textinput.go
=> Reset cursor in SetValue when initial pos is 0

viewport/viewport.go
Gets rid of a (dupe) magic number.
=> Use a const for the mouse wheel delta in viewport

progress/progress.go, spinner/spinner.go
Removes a few unwanted linter warnings.
=> Mark innocuous numbers as nolint

paginator/paginator.go, viewport/viewport.go
=> Fix godocs for various types and functions

textinput/textinput.go
This actually uncovered a few ineffective assignments, particularly in deleteWordRight.
=> Drop naked returns in textinput model

timer/timer.go
This update contains various quality-of-life improvements for the forthcoming timer component.
* Add IDs to timers
* Add IDs to timer-related messages
* Ignore messages from other timers
* Add `Timeout` property to `TickMsg`
* ~Send a `TickMsg` with timeout flag on timeout in addition to a `TimeoutMsg`~
* Add `Start()`, `Stop()`, and `Toggle()` commands to timer
* Add `Timedout()` method to timer model
* Add `Running()` method to timer model
=> Various timer improvements

help/help.go, list/list.go, progress/progress.go, textinput/textinput.go
Cleanup various things the inter found.
=> Various linter cleanups

README.md, key/key.go
=> Fix key binding documentation

list/list.go
Hi,
improved the documentation of `InsertItem`
=> Improve insert item documentation

README.md
This update adds some great Bubbles libraries from @76creates and @calyptia.
=> docs: add more libs to Additional Bubbles in the README

list/list.go
Return "No items found." when list is empty
Fixes: 4e18245481ab ("Add list bubble")
=> fix(list): rendering empty list

list/list.go
Probably fixes https://github.com/charmbracelet/bubbles/issues/130
@meowgorithm Sry, had to close the old PR, because I needed my master.
=> Fix padding in titlebar when nothing is displayed

textinput/textinput.go
=> fix(textinput): support KeySpace in present and future Bubble Tea versions

list/list.go
=> docs(list): fix linting errors

list/list.go
I've added a helper method `IsFiltered()` to easily check whether a list is filtered or not.
=> add helper method to check if list is filtered

textarea/textarea.go
Change textarea placeholder color (`240`) to match textinput.
=> Change Textarea Placeholder Color to match Textinput

viewport/viewport.go
Guard against negative string repetitions in HighPerformanceRendering viewport.
=> Fix HighPerformanceRendering Negative Repeat Count

textinput/textinput.go
Add key binding for Ctrl+H to backspace text
=> Ctrl+H backspaces text

README.md
Uses `<picture />` for responsive mobile images and `max-width`
=> Responsive GIFs for Mobile READMEs

key/key.go
=> Avoid recomputing the key representation in Matches

textarea/textarea.go
=> textarea: amortize heap allocs in Value

README.md
- docs: change tea{,party} to bubbletea
- docs: add table bubble to README
=> Add Table Bubble to README

cursor/cursor.go
Found bug using [catwalk](https://github.com/knz/catwalk).
Fixes #229.
cc @maaslalani
=> fix(cursor): apply TextStyle inline

.github/workflows/lint-soft.yml, .golangci-soft.yml, .golangci.yml, key/key.go, paginator/paginator.go, table/table.go, viewport/viewport.go
=> ci: add separate sets of hard- and soft-enforced linters

textinput/textinput.go
This PR fixes the cursor movement for the `input` bubble.
=> Fix SetValue cursor movement

help/help.go
=> fix(help): full help renders fully when width is unset.

go.mod, table/table.go
Exposes a `table`'s rows through `func Rows() []Row`
=> Table: expose rows

table/table.go
Adds `SetColumns` method for setting columns.
=> feat(table): add `SetColumns` method to set columns

textinput/textinput.go
=> fix(textinput): KeyMap typo

list/list.go
Hi, this PR allows to enable "infinite scrolling" for the `list` bubble.
=> feat(list): infinite scrolling

spinner/spinner.go
Handy for animating the three periods after a string, i.e. "Loading..."
=> feat(spinner): periods of ellipsis

textinput/textinput.go
Unicode character encoding error
#420
=> fix: Unicode character encoding error

go.mod, go.sum, viewport/viewport.go
Supersedes: https://github.com/charmbracelet/bubbles/pull/447
=> feat: upgrade bubbletea and remove deprecated code

textinput/textinput.go
Reverts charmbracelet/bubbles#442
=> Revert "fix (textinput): do not resize based on placeholder"

textarea/textarea.go
=> fix(textarea): correctly trim incoming paste

filepicker/filepicker.go
This PR introduces the following properties:
* `ShowSize`
* `ShowPermissions`
to allow for more compact file picker views.
=> Optional File Permissions and File Size

textinput/textinput.go
Fixes a possible panic in case CurrentSuggestion is called on an empty input.
=> fix(textinput): out of range panic if no matched suggestions

table/table.go
Same as Rows function but for Columns.
=> feat(table): Add column return function

table/table.go
=> (fix)table: don't render a column with a width <= 0

table/table.go
Added FullHelp and ShortHelp methods to table.Keymap
=> feat(table): implement help.Keymap interface and add quit mapping

.github/CODEOWNERS, progress/progress.go, table/table.go, textarea/textarea.go
This brings new stuff from `master` into `beta` (which is mostly textarea) stuff. Note that tests still need to be updated.
=> Update Beta Branch

go.mod, go.sum, help/help_test.go, help/testdata/TestFullHelp/full_help_20_width.golden, help/testdata/TestFullHelp/full_help_30_width.golden, help/testdata/TestFullHelp/full_help_40_width.golden
This is a small test to support and prove @luevano's fix in #554.
=> chore(help): add small full help test

README.md
https://github.com/charmbracelet/bubbles/tree/update-contributing?tab=readme-ov-file#contributing
=> docs: update contributing guidelines

textarea/textarea.go
Supersedes: https://github.com/charmbracelet/bubbles/tree/v2-revert-real-area
=> (v2) Revert cursor position from v2-area

go.mod, go.sum, textarea/textarea.go
This returns the current cursor position accounting any soft-wrapped lines and multi-rune characters.
=> feat(textarea): add CursorPosition method

textinput/textinput.go, textinput/textinput_test.go
This can look confusing in forms otherwise.
=> Don't render suggestions when textinput is not focused.

go.mod, textarea/textarea.go, textarea/textarea_test.go
=> fix(textarea): placeholder with chinese chars

README.md
=> Remove Charm

filepicker/filepicker.go, textarea/textarea.go, textarea/textarea_test.go
this allows to get the word under the cursor.
a word in this case is a space delimited string.
=> feat(textarea): get the word under the cursor
